version: "3.3"

services:
  db:
    image: postgres:11.4
    container_name: database-lis
    environment:
      - POSTGRES_DB=lis-beer
      - POSTGRES_PASSWORD=development
      - POSTGRES_USER=development
    ports:
      - "5432:5432"
    volumes:
      - ./db/roles.sql:/docker-entrypoint-iniydb.d/roles.sql
    restart: always