on:
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build -x test

  docker:
    name: Build and Run docker
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Build and Run Docker container
        run: docker-compose -f ./docker-compose-dev.yml up -d
        working-directory: .

  e2e:
    name: Run end to end tests
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm install
      - run: npm run test