name: CI/CD

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build -x test
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1" 
    - name: Print dir
      run: echo "$(ls)"
    - name: Upload package to S3 bucket
      run: aws s3 cp /build/libs/*.jar s3://lis-beer/
    - name: Create new ElasticBeanstalk Application Version
      run: |
          aws elasticbeanstalk create-application-version \
          --application-name lis-beer-deploy \
          --source-bundle S3Bucket="lis-beer",S3Key="*.jar" \
          --version-label "ver-${{ github.sha }}" \
          --description "commit-sha-${{ github.sha }}"
    - name: Deploy new ElasticBeanstalk Application Version
      run: aws elasticbeanstalk update-environment --environment-name Lisbeerdeploy-env --version-label "ver-${{ github.sha }}"
    
        
    
